### ISSUE TITLE
Backpack is empited after retrieving it from corpse

### ISSUE THREAD

**Issue by TheGordinho** [LunaPixelStudios/Better-Minecraft#292]
### Describe the Bug

If you retrive your backpack from your corpse while in creative and go back to survival before opening the backpack it will be cleared.
All the normal inventory will be kept 

### Reproduction Steps

1. Die in survival
2. Switch to creative
3. Retrieve itens
4. Go back to survival
5. Open backpack

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V6

### Optifine

No

**Comment by SharkieTV** [comment]
I am unable to reproduce this issue, can you show me a video? and are you on a server?

**Comment by TheGordinho** [comment]
> Try dying on one dimentiong while the bed is on the overworld
switch gamemodes
go back to the dimention you died 
get the backpack and equip it while on creative
switch gamemodes to survival
open the backpack with the hotkey

**Comment by SharkieTV** [comment]
Still unable but im not sure why you would equip it while being in creative as creative most likely creates a new backpack as that is how creative works, maybe if you paly survival dont go into creative?

**Comment by MrCrayfish** [comment]
I can confirm the issue is there but it's very rare and hard to preproduce. I managed to get it once but after that no luck. I've obviously had people report to my repo but I don't believe the issue stems from my mod (based on what I've read and the bug not existing when using without Corpse).

Corpse however is throwing the followng warning every time a packet is sent, which could be related. 
`Unknown custom packet identifier: corpse:default`

Issue from my repo for reference
https://github.com/MrCrayfish/Backpacked/issues/110
