### ISSUE TITLE
Mob audio bug [Forge]

### ISSUE THREAD

**Issue by JadenDoll** [LunaPixelStudios/Better-Minecraft#469]
Having audio issues, can't hear "standard" mobs (i.e. Zombies, Skeletons, Pillagers(normal, not firework), etc). I attempted to make another world, it worked at first. Logged in today and it got worse, I cant hear zombie variants, only footsteps. Also damage sound is gone, menu sound, eating sound. (FORGE 1.18)

**Comment by SharkieTV** [comment]
Im unable to reproduce this issue, have you tried restarting your game?

**Comment by crockfordUni** [comment]
I'm Having the exact same issue I have no mob sounds I get no player sounds nothing has changed since last played haven't even turned on computer since last playing I'm also not getting any weapon sounds either this was from lunch of the game so I've done nothing new I have tried restarting its also has no menu sounds as soon as I start up the game

**Comment by HGCKharn** [comment]
I have been experiencing the exact same issue for the past week and a half - no mob sounds, no rain sounds, no combat, no eating sounds.
I have restarted my game a number of times, even my computer.  Sometimes it comes back, other times it don't. Lately, more often it doesn't.

**Comment by dachompchomp** [comment]
im having this problem and its really dumb and i cant hear mobs and cant really hear anything this is on 12.0 not 12.5

**Comment by SharkieTV** [comment]
Better Minecraft 1.18.2 is now Discontinued and will be working on 1.19 isntead.
