### ISSUE TITLE
No Menu and Damage sound

### ISSUE THREAD

**Issue by Flivu** [LunaPixelStudios/Better-Minecraft#513]
### Describe the Bug

When Playing Better Minecraft in 1.18.2 i miss some Sound. As an Example Menu and Damage sound.

### Reproduction Steps

1.Checkt the Sound settings and had every setting on 100% (Ingame and on my PC)
2. Deinstall and reinstall the Modpack (Several Versions tried), (the 1.19 version works)
3. Tried with and without Headphones
4. Block building sound and other Sounds (Animals etc.) work.
5. Tried with Forge and Fabric (Both the same)
6.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V10, V11, V11.5, V12 (V12.5 worked)

### Optifine

No

**Comment by SharkieTV** [comment]
If you are having issues with both modpacks it has to be your pc.
Otherwise its some mod causing a specific issue with your pc and I cant really tell you what as their isnt any cahnges to audio in forge but just 1 mod in fabric and that is dynamic sound filters. you can try removing that but other than that I cant help much
