### ISSUE TITLE
Crash near Graveyard structure

### ISSUE THREAD

**Issue by ReducedRose** [LunaPixelStudios/Better-Minecraft#78]
### Describe the Bug

Server crashes when near a specific area on server, possibly due to a Graveyard structure

### Crash Report or Log

https://pastebin.com/2CTmY12b

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v15

### Optifine

No

### Other Mods

No

**Comment by SharkieTV** [comment]
See if Removing serene seasons mod fixes it?

**Comment by Arkytorous** [comment]
I been having the same issue, removing the serene seasons mod doesn't fix the issue. I also tried deleting the chunks however that didn't fix it either.

**Comment by SharkieTV** [comment]
If you are sure its a graveyard crashing your game remove the graveyard mod and see if that fixes it?

**Comment by Gargles** [comment]
im having the same issue as well, have deleted graveyard and serene seasons, removed the chunks the structure was originally in and it doesn't change the outcome

**Comment by SharkieTV** [comment]
No Response

**Comment by Arkytorous** [comment]
It turns out it wasn't the graveyard mod, everytime I load into specific chunks the server crashes and when I join back it instantly shuts down the server. 


The crashlog is here:
[crash-2022-02-05_10.34.58-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/8007829/crash-2022-02-05_10.34.58-server.txt)

**Comment by switchnlade** [comment]
Update to v16 or update the Hedgehog mod
